#!/usr/bin/env bash
# Install your load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
confg='/etc/haproxy/haproxy.cfg'

echo "
frontend http
    bind *:80
    mode http
    default_backend icap_pool

backend icap_pool
    balance roundrobin
    mode http
	server 3464-web-01 23.21.15.186:80 check
	server 3464-web-02 34.138.82.74:80 check" | sudo tee -a $confg
sudo service haproxy restart
