#!/usr/bin/env bash
# Configure HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

path="/etc/haproxy/haproxy.cfg"
echo "
frontend http
    bind *:80
    mode http
    default_backend icap_pool
backend icap_pool
    balance roundrobin
    mode http
    server 3464-web-01 34.74.110.79 check
    server 3464-web-02 34.235.152.2 check" | sudo tee -a $path > /dev/null

sudo service haproxy start
sudo service nginx restart
