#!/usr/bin/env bash
# mysql installation verion 5.7.37
sudo apt update
sudo apt install wget -y
wget https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.12-1_all.deb
# select ubuntu bionic
# mysql 8.0
# mysql 5.7
# currently selected 5.7 ; then tab and ok
sudo apt-get update
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29
sudo apt-get update
sudo apt-cache policy mysql-server
sudo apt install -f mysql-community-client=5.7.37-1ubuntu18.04 -y
# in case of error use this two lines of code
sudo apt install -f mysql-client=5.7.37-1ubuntu18.04 -y
sudo apt install -f mysql-community-server=5.7.37-1ubuntu18.04 -y
# select password root
mysql --version
mysql -u root -p