#!/usr/bin/env bash
#PID

echo "$$" > /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command" && rm /var/run/my.pid && exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm /var/run/my.pid && exit' SIGQUIT
done