#!/usr/bin/env bash
# file

cont=1
while [ $cont -le 100 ]
do
        if ! ((cont%15))
        then
                echo "FizzBuzz"
        elif ! ((cont%3))
        then
                echo "Fizz"
        elif ! ((cont%5))
        then
                echo "Buzz"
        else
                echo "$cont"
        fi
        ((cont++))
done