#!/usr/bin/env bash
#conditional

cont=1
while [ $cont -lt 20 ]
do
	echo "$cont"
	case $cont in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( cont++ ))
done
