#!/usr/bin/env bash
# file

if [ -e "school" ]
then
    echo "school fiel exists"
    if [ -s "school" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "school" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file dos not exist"
fi