#!/usr/bin/env bash
user_change="/etc/nginx/nginx.conf";
sed -i "s|www-data|nginx|" $user_change
path="/etc/nginx/sites-available/default";
sed -i "s|80 default_server|8080 default_server" $path
sudo -u nginx service nginx restart
